[package]
name = "gltf_viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
colog = "1.3.0"
log = "0.4.27"
vulkano = "0.35.1"
vulkano-shaders = "0.35.0"
vulkano-util = "0.35.0"
winit = "0.30.9"
